version: "3"

services:
  db:
    image: mysql:5.7
    container_name: envole_wordpress_db
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
#    env_file:
#      - .env
    ports:
    - '5306:3306'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: envole_wordpress_dev
    ports:
    - '8001:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
#    env_file:
#      - .env
    volumes:
    - "$PWD:/var/www/html"
    - "$PWD/.docker/backup:/tmp/backup"
    - "$PWD/.docker/log:/tmp/log"
volumes:
  db_data: {}
